#!/bin/bash
function resolve_file() {
	local target_file=$1

	cd `dirname $target_file`
	target_file=`basename $target_file`

	# Iterate down a (possible) chain of symlinks
	while [ -L "$target_file" ]
	do
			target_file=`readlink $target_file`
			cd `dirname $target_file`
			target_file=`basename $target_file`
	done

	# Compute the canonicalized name by finding the physical path 
	# for the directory we're in and appending the target file.
	local readonly phys_dir=`pwd -P`
	echo "$phys_dir/$target_file"
}

readonly THIS_FILE=$(resolve_file ${BASH_SOURCE[0]})
readonly DIR=$(dirname "$THIS_FILE")

readonly RUST_COMPILER=$DIR/rs-parser/target/debug/rs-parser

function print_help() {
	cat <<HELP
Usage:
	tzio [--rust|--clj] <filename>

Options:
	-h, --help: Prints this help message
	--rust: Use the rust compiler
	--clj: Use the Clojure compiler
HELP
	exit 0
}

compiler=
case $1 in
	-h|--help) print_help ;;
	--rust)
		compiler=$RUST_COMPILER
		shift 1 ;;
	*) compiler=$RUST_COMPILER ;;
esac

input_file=$1
output_dir=$2
$compiler $input_file $output_dir